import Link from 'next/link';
import { notFound } from 'next/navigation';

const guides: Record<string, { name: string; abbr: string; icon: string; topics: string[]; content: string; keyLaws: string[]; legalNotes: string[] }> = {
  'alabama': { name: 'Alabama', abbr: 'AL', icon: '\u{1f33f}', topics: ['Foreclosure', 'Property Tax', 'Business Law', 'Family Law'], content: 'Alabama has specific legal requirements for real estate transactions, business formation, and family law matters. The state follows common law traditions with some unique statutory provisions.\n\n## Key Legal Areas in Alabama\n\n### Real Estate Law\nAlabama requires specific disclosures for real estate transactions and has unique property tax assessment procedures. The state uses a system of ad valorem taxation for property.\n\n### Foreclosure\nAlabama is a judicial foreclosure state, meaning foreclosure proceedings must go through the court system. The process typically takes 60-90 days from filing to sale.\n\n### Family Law\nAlabama follows equitable distribution for property division in divorce cases. The state has specific child custody guidelines and alimony provisions.\n\n### Business Law\nAlabama offers various business entity types including LLCs, corporations, and partnerships. The state has specific filing requirements with the Secretary of State.', keyLaws: ['Alabama Code Title 35 (Property)', 'Alabama Code Title 10 (Corporations)', 'Alabama Code Title 30 (Marriage and Divorce)', 'Alabama Rules of Civil Procedure'], legalNotes: ['Judicial foreclosure required', 'Property tax assessment varies by county', 'Equitable distribution in divorce', 'Specific business filing requirements'] },
  'alaska': { name: 'Alaska', abbr: 'AK', icon: '\u2744\ufe0f', topics: ['Native Claims', 'Oil and Gas', 'Homesteading', 'Property Rights'], content: 'Alaska has unique legal considerations due to its remote location, natural resources, and Native American land claims. The state has specific laws regarding oil and gas rights and property ownership.\n\n## Key Legal Areas in Alaska\n\n### Native Land Claims\nAlaska has complex laws regarding Native American land claims and the Alaska Native Claims Settlement Act (ANCSA). Understanding these laws is crucial for real estate transactions.\n\n### Oil and Gas Rights\nAlaska has specific laws governing oil and gas rights, including surface and mineral rights separation. The state has a production tax system for oil and gas.\n\n### Property Rights\nAlaska has unique homesteading laws and property rights protections. The state has specific requirements for property transfers and recording.\n\n### Family Law\nAlaska has specific family law provisions including child custody guidelines and spousal support requirements.', keyLaws: ['Alaska Statutes Title 9 (Code of Civil Procedure)', 'Alaska Statutes Title 13 (Decedents Estates)', 'Alaska Statutes Title 25 (Marital Relations)', 'Alaska Native Claims Settlement Act'], legalNotes: ['Complex Native land claims', 'Oil and gas rights separate from surface', 'Specific homesteading provisions', 'Unique property transfer requirements'] },
  'arizona': { name: 'Arizona', abbr: 'AZ', icon: '\u{1f335}', topics: ['Water Rights', 'Community Property', 'Business Formation', 'Real Estate'], content: 'Arizona has specific laws regarding water rights, community property, and business formation. The state is a community property state with unique real estate regulations.\n\n## Key Legal Areas in Arizona\n\n### Water Rights\nArizona has a prior appropriation system for water rights, which is crucial for real estate development and agricultural operations.\n\n### Community Property\nArizona is a community property state, meaning most property acquired during marriage is jointly owned. This affects property division in divorce proceedings.\n\n### Business Formation\nArizona offers various business entity types and has specific filing requirements with the Corporation Commission.\n\n### Real Estate\nArizona has specific disclosure requirements for real estate transactions and unique property tax assessment procedures.', keyLaws: ['Arizona Revised Statutes Title 25 (Marriage)', 'Arizona Revised Statutes Title 33 (Property)', 'Arizona Revised Statutes Title 29 (Corporations)', 'Arizona Water Code'], legalNotes: ['Prior appropriation water rights', 'Community property state', 'Specific business filing requirements', 'Real estate disclosure requirements'] },
  'arkansas': { name: 'Arkansas', abbr: 'AR', icon: '\u{1f341}', topics: ['Property Tax', 'Business Law', 'Family Law', 'Real Estate'], content: 'Arkansas has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutes governing real estate transactions and business operations.\n\n## Key Legal Areas in Arkansas\n\n### Property Tax\nArkansas has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\nArkansas offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Family Law\nArkansas follows equitable distribution for property division in divorce cases and has specific child custody guidelines.\n\n### Real Estate\nArkansas has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Arkansas Code Title 14 (Limiteation of Actions)', 'Arkansas Code Title 26 (Taxation)', 'Arkansas Code Title 9 (Family Law)', 'Arkansas Code Title 18 (Corporations)'], legalNotes: ['Property tax exemptions available', 'Equitable distribution in divorce', 'Specific business filing requirements', 'Real estate disclosure requirements'] },
  'california': { name: 'California', abbr: 'CA', icon: '\u{1f334}', topics: ['Rent Control', 'Employment Law', 'Business Regulations', 'Tenant Rights'], content: 'California has some of the most comprehensive tenant protections in the US, including rent control in certain cities and statewide just cause eviction requirements. The state is known for its strong consumer protection laws and employment regulations.\n\n## Key Legal Areas in California\n\n### Tenant Rights\nCalifornia provides extensive tenant protections including the Tenant Protection Act (AB 1482) which limits rent increases to 5% plus inflation and requires just cause for eviction after 12 months of tenancy. Cities like San Francisco, Los Angeles, and Berkeley have additional rent control ordinances.\n\n### Employment Law\nCalifornia has strict employment laws including minimum wage requirements, meal and rest break mandates, overtime pay requirements, and anti-discrimination protections. The state follows the at-will employment doctrine but with significant exceptions.\n\n### Business Regulations\nCalifornia requires businesses to comply with numerous state regulations including the California Consumer Privacy Act (CCPA), employment standards, and environmental regulations.\n\n### Real Estate\nCalifornia has specific disclosure requirements for real estate transactions, including natural hazard disclosures, lead paint disclosures, and material fact disclosures.', keyLaws: ['California Civil Code sections 1940-1954 (Landlord-Tenant)', 'California Labor Code (Employment)', 'California Business and Professions Code', 'California Consumer Privacy Act (CCPA)'], legalNotes: ['Rent increases limited to 5% plus inflation statewide', 'Just cause eviction required after 12 months', 'Security deposit limits: 2 months (unfurnished), 3 months (furnished)', 'Lead paint disclosure required for pre-1978 properties'] },
  'colorado': { name: 'Colorado', abbr: 'CO', icon: '\u26f0\ufe0f', topics: ['Cannabis Law', 'Water Rights', 'Real Estate', 'Business Law'], content: 'Colorado has unique legal considerations due to cannabis legalization, water rights complexities, and growing real estate market. The state has specific regulations for businesses and property owners.\n\n## Key Legal Areas in Colorado\n\n### Cannabis Law\nColorado was one of the first states to legalize recreational cannabis. The state has specific licensing, taxation, and compliance requirements for cannabis businesses.\n\n### Water Rights\nColorado follows the prior appropriation doctrine for water rights, which is crucial for real estate and agricultural operations.\n\n### Real Estate\nColorado has specific disclosure requirements for real estate transactions and unique property tax assessment procedures.\n\n### Business Law\nColorado offers various business entity types and has specific filing requirements with the Secretary of State.', keyLaws: ['Colorado Revised Statutes Title 38 (Property, Real and Personal)', 'Colorado Revised Statutes Title 7 (Corporations and Associations)', 'Colorado Marijuana Enforcement Division Regulations', 'Colorado Water Right Determination and Administration Act'], legalNotes: ['Cannabis legalization with specific regulations', 'Prior appropriation water rights', 'Real estate disclosure requirements', 'Specific business entity requirements'] },
  'connecticut': { name: 'Connecticut', abbr: 'CT', icon: '\u{1f342}', topics: ['Probate', 'Property Tax', 'Business Law', 'Family Law'], content: 'Connecticut has specific legal requirements for probate, property tax, and business formation. The state has unique statutory provisions governing real estate transactions and family law matters.\n\n## Key Legal Areas in Connecticut\n\n### Probate\nConnecticut has a unique probate court system with specific procedures for estate administration and guardianship matters.\n\n### Property Tax\nConnecticut has specific property tax assessment and collection procedures. The state offers various exemptions and deferrals for qualifying property owners.\n\n### Business Law\nConnecticut offers various business entity types and has specific filing requirements with the Secretary of the State.\n\n### Family Law\nConnecticut follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Connecticut General Statutes Title 47 (Land and Water)', 'Connecticut General Statutes Title 33 (Corporations)', 'Connecticut General Statutes Title 46b (Family Relations)', 'Connecticut Probate Court Procedures'], legalNotes: ['Unique probate court system', 'Property tax exemptions available', 'Equitable distribution in divorce', 'Specific business filing requirements'] },
  'delaware': { name: 'Delaware', abbr: 'DE', icon: '\u{1f333}', topics: ['Corporate Law', 'Chancery Court', 'Business Formation', 'Real Estate'], content: 'Delaware is known as the corporate capital of the US due to its business-friendly laws and specialized Court of Chancery. The state has specific requirements for business formation and governance.\n\n## Key Legal Areas in Delaware\n\n### Corporate Law\nDelaware has the most comprehensive corporate law in the US, with the Delaware General Corporation Law (DGCL) being the standard for many corporations.\n\n### Chancery Court\nDelaware Court of Chancery is a specialized court that handles corporate and business disputes. It has a long history of precedent in corporate law.\n\n### Business Formation\nDelaware offers various business entity types and has specific filing requirements with the Division of Corporations.\n\n### Real Estate\nDelaware has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Delaware Code Title 8 (Corporations)', 'Delaware Code Title 25 (Property)', 'Delaware Code Title 13 (Domestic Relations)', 'Delaware Court of Chancery Rules'], legalNotes: ['Premier corporate law jurisdiction', 'Specialized Court of Chancery', 'Business-friendly formation requirements', 'Specific real estate disclosure requirements'] },
  'florida': { name: 'Florida', abbr: 'FL', icon: '\u{1f30a}', topics: ['Homestead Exemption', 'Probate', 'No State Income Tax', 'Business Law'], content: 'Florida offers strong homestead protections and no state income tax, making it attractive for retirees and businesses. The state has specific probate procedures and real estate regulations.\n\n## Key Legal Areas in Florida\n\n### Homestead Protection\nFlorida has one of the strongest homestead protections in the country, protecting primary residences from most creditors. The exemption covers unlimited value for qualifying properties.\n\n### Probate\nFlorida has specific probate procedures that differ from many other states, including summary administration for smaller estates and formal administration for larger ones.\n\n### Real Estate\nFlorida has specific disclosure requirements for real estate transactions and condominium associations. The state requires disclosure of material facts about properties.\n\n### Business Law\nFlorida offers a business-friendly environment with no state income tax and limited regulations. The state has specific filing requirements with the Division of Corporations.', keyLaws: ['Florida Statutes Chapter 83 (Landlord-Tenant)', 'Florida Probate Code (Chapter 731-735)', 'Florida Condominium Act (Chapter 718)', 'Florida Business Corporation Act (Chapter 607)'], legalNotes: ['Strong homestead protections', 'No state income tax', '3-day notice for non-payment of rent', 'Condominium associations have specific requirements'] },
  'georgia': { name: 'Georgia', abbr: 'GA', icon: '\u{1f340}', topics: ['Business Law', 'Real Estate', 'Family Law', 'Property Tax'], content: 'Georgia has specific legal requirements for business formation, real estate transactions, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Georgia\n\n### Business Law\nGeorgia offers various business entity types and has specific filing requirements with the Secretary of State. The state has a growing business community.\n\n### Real Estate\nGeorgia has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\nGeorgia follows equitable distribution for property division in divorce cases and has specific child custody guidelines.\n\n### Property Tax\nGeorgia has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.', keyLaws: ['Georgia Code Title 44 (Property)', 'Georgia Code Title 14 (Corporations)', 'Georgia Code Title 19 (Domestic Relations)', 'Georgia Code Title 48 (Revenue and Taxation)'], legalNotes: ['Business-friendly environment', 'Equitable distribution in divorce', 'Homestead exemptions available', 'Specific real estate disclosure requirements'] },
  'hawaii': { name: 'Hawaii', abbr: 'HI', icon: '\u{1f345}', topics: ['Land Ownership', 'Leasehold', 'Business Law', 'Real Estate'], content: 'Hawaii has unique legal considerations due to land ownership restrictions, leasehold systems, and specific real estate regulations. The state has specific requirements for property transactions and business operations.\n\n## Key Legal Areas in Hawaii\n\n### Land Ownership\nHawaii has specific restrictions on land ownership, particularly for non-residents. The state has unique requirements for property transfers and recording.\n\n### Leasehold\nHawaii has a unique leasehold system for many properties, particularly in resort areas. Understanding leasehold terms is crucial for property transactions.\n\n### Business Law\nHawaii offers various business entity types and has specific filing requirements with the Department of Commerce and Consumer Affairs.\n\n### Real Estate\nHawaii has specific disclosure requirements for real estate transactions and unique property tax assessment procedures.', keyLaws: ['Hawaii Revised Statutes Title 28 (Property)', 'Hawaii Revised Statutes Title 41 (Corporations)', 'Hawaii Revised Statutes Title 573 (Conveyances)', 'Hawaii Land Court Rules'], legalNotes: ['Unique land ownership restrictions', 'Leasehold system common', 'Specific business filing requirements', 'Real estate disclosure requirements'] },
  'idaho': { name: 'Idaho', abbr: 'ID', icon: '\u{1f332}', topics: ['Property Rights', 'Business Law', 'Real Estate', 'Water Rights'], content: 'Idaho has specific legal requirements for property rights, business formation, and water rights. The state has unique statutory provisions governing real estate transactions and business operations.\n\n## Key Legal Areas in Idaho\n\n### Property Rights\nIdaho has specific property rights protections and unique requirements for property transfers and recording.\n\n### Business Law\nIdaho offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\nIdaho has specific disclosure requirements for real estate transactions and unique property tax assessment procedures.\n\n### Water Rights\nIdaho follows the prior appropriation doctrine for water rights, which is crucial for real estate and agricultural operations.', keyLaws: ['Idaho Code Title 55 (Property, Real and Personal)', 'Idaho Code Title 30 (Corporations)', 'Idaho Code Title 32 (Corporations)', 'Idaho Water Rights statutes'], legalNotes: ['Prior appropriation water rights', 'Specific property transfer requirements', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'illinois': { name: 'Illinois', abbr: 'IL', icon: '\u{1f3d9}\ufe0f', topics: ['Chicago RLTO', 'Property Tax', 'Business Law', 'Tenant Rights'], content: 'Illinois, particularly Chicago, has the Residential Landlord Tenant Ordinance (RLTO) with strong tenant protections. The state has complex tax structures and business regulations.\n\n## Key Legal Areas in Illinois\n\n### Chicago RLTO\nChicago has one of the most comprehensive tenant protection ordinances in the country, the Residential Landlord Tenant Ordinance (RLTO). It requires specific disclosures, limits on security deposits, and additional tenant rights.\n\n### Property Tax\nIllinois has complex property tax systems with multiple taxing districts and assessment procedures. The state has some of the highest property tax rates in the nation.\n\n### Business Law\nIllinois has specific business regulations including the Illinois Business Corporation Act and various licensing requirements.\n\n### Employment Law\nIllinois follows at-will employment but has specific protections including the Illinois Human Rights Act and recent amendments regarding employee rights.', keyLaws: ['Illinois Residential Landlord and Tenant Act', 'Illinois Business Corporation Act', 'Illinois Human Rights Act', 'Chicago Residential Landlord and Tenant Ordinance (RLTO)'], legalNotes: ['Chicago RLTO provides strong tenant protections', 'Security deposit interest required in Chicago', '5-day notice for non-payment of rent', 'Just cause eviction in Chicago'] },
  'indiana': { name: 'Indiana', abbr: 'IN', icon: '\u{1f33e}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'Indiana has specific legal requirements for property tax, business formation, and real estate transactions. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Indiana\n\n### Property Tax\nIndiana has specific property tax assessment and collection procedures. The state offers homestead deductions for qualifying property owners.\n\n### Business Law\nIndiana offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\nIndiana has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\nIndiana follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Indiana Code Title 32 (Property)', 'Indiana Code Title 23 (Business and Corporate Affairs)', 'Indiana Code Title 31 (Domestic Relations)', 'Indiana Code Title 6 (Taxation)'], legalNotes: ['Property tax deductions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'iowa': { name: 'Iowa', abbr: 'IA', icon: '\u{1f33e}', topics: ['Agricultural Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Iowa has specific legal requirements for agricultural law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Iowa\n\n### Agricultural Law\nIowa has specific laws governing agricultural operations, including land use, environmental regulations, and farm business structures.\n\n### Property Tax\nIowa has specific property tax assessment and collection procedures. The state offers various exemptions and credits for qualifying property owners.\n\n### Business Law\nIowa offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\nIowa has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Iowa Code Title IV (Property and Property Transactions)', 'Iowa Code Title XVI (Corporations)', 'Iowa Code Title V (Domestic Relations)', 'Iowa Code Title IV (Taxation)'], legalNotes: ['Agricultural law considerations', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'kansas': { name: 'Kansas', abbr: 'KS', icon: '\u{1f33e}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Water Rights'], content: 'Kansas has specific legal requirements for property tax, business formation, and water rights. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Kansas\n\n### Property Tax\nKansas has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\nKansas offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\nKansas has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Water Rights\nKansas follows the prior appropriation doctrine for water rights, which is crucial for real estate and agricultural operations.', keyLaws: ['Kansas Statutes Article 5 (Property and Conveyances)', 'Kansas Statutes Article 17 (Corporations)', 'Kansas Statutes Article 23 (Marriage and Domestic Relations)', 'Kansas Water Appropriation Act'], legalNotes: ['Prior appropriation water rights', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'kentucky': { name: 'Kentucky', abbr: 'KY', icon: '\u{1f340}', topics: ['Coal Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Kentucky has specific legal requirements for coal law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Kentucky\n\n### Coal Law\nKentucky has specific laws governing coal mining operations, including environmental regulations and land reclamation requirements.\n\n### Property Tax\nKentucky has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\nKentucky offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\nKentucky has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Kentucky Revised Statutes Title VIII (Property and Conveyances)', 'Kentucky Revised Statutes Title XXVII (Corporations)', 'Kentucky Revised Statutes Title XXXV (Domestic Relations)', 'Kentucky Coal Mining Laws'], legalNotes: ['Coal mining regulations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'louisiana': { name: 'Louisiana', abbr: 'LA', icon: '\u{1f336}\ufe0f', topics: ['Civil Law', 'Property Rights', 'Business Law', 'Family Law'], content: 'Louisiana is unique among US states because it follows a civil law system based on French and Spanish legal traditions. The state has specific requirements for property rights, business formation, and family law matters.\n\n## Key Legal Areas in Louisiana\n\n### Civil Law System\nLouisiana follows a civil law system rather than common law, which means court decisions are not binding precedent. The state\'s laws are codified in the Louisiana Civil Code.\n\n### Property Rights\nLouisiana has unique property rights protections, including community property laws and specific requirements for property transfers.\n\n### Business Law\nLouisiana offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Family Law\Louisiana has specific family law provisions including community property rules and child custody guidelines.', keyLaws: ['Louisiana Civil Code', 'Louisiana Revised Statutes Title 9 (Corporations)', 'Louisiana Revised Statutes Title 9:354 (Civil Code)', 'Louisiana Code of Civil Procedure'], legalNotes: ['Civil law system unique in US', 'Community property state', 'Specific property transfer requirements', 'Business filing requirements'] },
  'maine': { name: 'Maine', abbr: 'ME', icon: '\u{1f342}', topics: ['Coastal Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Maine has specific legal requirements for coastal law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Maine\n\n### Coastal Law\Maine has specific laws governing coastal properties, including setback requirements, wetland protections, and shoreland zoning.\n\n### Property Tax\nMaine has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Maine offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Maine has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Maine Revised Statutes Title 33 (Property and Conveyances)', 'Maine Revised Statutes Title 13-C (Maine Business Corporation Act)', 'Maine Revised Statutes Title 19-A (Domestic Relations)', 'Maine Coastal Wetland Protection Act'], legalNotes: ['Coastal law considerations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'maryland': { name: 'Maryland', abbr: 'MD', icon: '\u{1f341}', topics: ['Chancery Court', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Maryland has specific legal requirements for chancery court proceedings, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Maryland\n\n### Chancery Court\nMaryland has a specialized chancery court system that handles equity cases, including property disputes and business matters.\n\n### Property Tax\nMaryland has specific property tax assessment and collection procedures. The state offers homestead tax credits for qualifying property owners.\n\n### Business Law\Maryland offers various business entity types and has specific filing requirements with the Department of Assessments and Taxation.\n\n### Real Estate\Maryland has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Maryland Code Real Property Article', 'Maryland Code Corporations and Associations Article', 'Maryland Code Family Law Article', 'Maryland Chancery Court Rules'], legalNotes: ['Specialized chancery court', 'Homestead tax credits available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'massachusetts': { name: 'Massachusetts', abbr: 'MA', icon: '\u{1f331}', topics: ['Tenant Rights', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Massachusetts has specific legal requirements for tenant rights, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Massachusetts\n\n### Tenant Rights\nMassachusetts has some of the strongest tenant protections in the US, including rent control in certain cities and just cause eviction requirements.\n\n### Property Tax\Massachusetts has specific property tax assessment and collection procedures. The state offers residential exemptions for qualifying property owners.\n\n### Business Law\Massachusetts offers various business entity types and has specific filing requirements with the Secretary of the Commonwealth.\n\n### Real Estate\Massachusetts has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Massachusetts General Laws Chapter 186 (Tenements and Common Lodging Houses)', 'Massachusetts General Laws Chapter 171 (Co-operative Banks)', 'Massachusetts General Laws Chapter 156 (Business Corporations)', 'Massachusetts General Laws Chapter 239 (Summary Process for Possession of Land)'], legalNotes: ['Strong tenant protections', 'Residential exemptions available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'michigan': { name: 'Michigan', abbr: 'MI', icon: '\u{1f30a}', topics: ['Automobile Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Michigan has specific legal requirements for automobile law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Michigan\n\n### Automobile Law\Michigan has unique automobile insurance requirements, including no-fault insurance and specific personal injury protection provisions.\n\n### Property Tax\Michigan has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Michigan offers various business entity types and has specific filing requirements with the Department of Licensing and Regulatory Affairs.\n\n### Real Estate\Michigan has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Michigan Compiled Laws Chapter 554 (Conveyances and Mortgages)', 'Michigan Compiled Laws Chapter 450 (Corporations)', 'Michigan Compiled Laws Chapter 700 (Estates and Protected Individuals)', 'Michigan No-Fault Insurance Act'], legalNotes: ['No-fault automobile insurance', 'Homestead exemptions available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'minnesota': { name: 'Minnesota', abbr: 'MN', icon: '\u2744\ufe0f', topics: ['Land of 10000 Lakes', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Minnesota has specific legal requirements for lake property, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Minnesota\n\n### Lake Property\Minnesota has specific laws governing lake properties, including shoreland zoning, riparian rights, and wetland protections.\n\n### Property Tax\Minnesota has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Minnesota offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Minnesota has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Minnesota Statutes Chapter 507 (Conveyancing and Mortgages)', 'Minnesota Statutes Chapter 302A (Minnesota Business Corporation Act)', 'Minnesota Statutes Chapter 518 (Dissolution of Marriage)', 'Minnesota Shoreland Management Act'], legalNotes: ['Lake property regulations', 'Homestead exemptions available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'mississippi': { name: 'Mississippi', abbr: 'MS', icon: '\u{1f33f}', topics: ['Property Rights', 'Business Law', 'Real Estate', 'Family Law'], content: 'Mississippi has specific legal requirements for property rights, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Mississippi\n\n### Property Rights\nMississippi has specific property rights protections and unique requirements for property transfers and recording.\n\n### Business Law\Mississippi offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Mississippi has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Mississippi follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Mississippi Code Title 85 (Deeds and Other Conveyances)', 'Mississippi Code Title 79 (Corporations, Associations, and Partnerships)', 'Mississippi Code Title 93 (Domestic Relations)', 'Mississippi Code Title 27 (Taxation)'], legalNotes: ['Specific property transfer requirements', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'missouri': { name: 'Missouri', abbr: 'MO', icon: '\u{1f33e}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'Missouri has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Missouri\n\n### Property Tax\Missouri has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\Missouri offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Missouri has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Missouri follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Missouri Revised Statutes Title I (Chattels and Personal Property)', 'Missouri Revised Statutes Title III (Corporations)', 'Missouri Revised Statutes Title XLV (Domestic Relations)', 'Missouri Revised Statutes Title XIV (Revenue and Taxation)'], legalNotes: ['Property tax exemptions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'montana': { name: 'Montana', abbr: 'MT', icon: '\u26f0\ufe0f', topics: ['Mining Law', 'Property Rights', 'Business Law', 'Real Estate'], content: 'Montana has specific legal requirements for mining law, property rights, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Montana\n\n### Mining Law\Montana has specific laws governing mining operations, including environmental regulations and mineral rights.\n\n### Property Rights\Montana has specific property rights protections and unique requirements for property transfers and recording.\n\n### Business Law\Montana offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Montana has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Montana Code Annotated Title 70 (Property, Personal)', 'Montana Code Annotated Title 35 (Corporations, Partnerships, Associations)', 'Montana Code Annotated Title 40 (Domestic Relations)', 'Montana Metal and Coal Mining Act'], legalNotes: ['Mining law regulations', 'Specific property transfer requirements', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'nebraska': { name: 'Nebraska', abbr: 'NE', icon: '\u{1f33e}', topics: ['Agricultural Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Nebraska has specific legal requirements for agricultural law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Nebraska\n\n### Agricultural Law\Nebraska has specific laws governing agricultural operations, including land use, environmental regulations, and farm business structures.\n\n### Property Tax\Nebraska has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Nebraska offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Nebraska has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Nebraska Revised Statutes Chapter 76 (Real Property)', 'Nebraska Revised Statutes Chapter 21 (Corporations)', 'Nebraska Revised Statutes Chapter 42 (Domestic Relations)', 'Nebraska Revenue and Taxation laws'], legalNotes: ['Agricultural law considerations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'nevada': { name: 'Nevada', abbr: 'NV', icon: '\u{1f3b0}', topics: ['Gaming Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Nevada has specific legal requirements for gaming law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Nevada\n\n### Gaming Law\Nevada has comprehensive gaming regulations that govern all aspects of casino operations, including licensing, taxation, and compliance requirements.\n\n### Property Tax\Nevada has specific property tax assessment and collection procedures. The state offers various exemptions and deferrals for qualifying property owners.\n\n### Business Law\Nevada offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Nevada has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Nevada Revised Statutes Title 10 (Conveyances of Real Property)', 'Nevada Revised Statutes Title 78 (Corporations, Partnerships, and Limited Liability Companies)', 'Nevada Revised Statutes Title 125 (Marriage and Domestic Relations)', 'Nevada Gaming Control Act'], legalNotes: ['Gaming law regulations', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'new-hampshire': { name: 'New Hampshire', abbr: 'NH', icon: '\u{1f342}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'New Hampshire has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in New Hampshire\n\n### Property Tax\New Hampshire relies heavily on property taxes since there is no state income tax or sales tax. The state has specific assessment and collection procedures.\n\n### Business Law\New Hampshire offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\New Hampshire has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\New Hampshire follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['New Hampshire Revised Statutes Title 47 (Property and Conveyances)', 'New Hampshire Revised Statutes Title 27 (Corporations, Associations, and Asset Protection)', 'New Hampshire Revised Statutes Title 43 (Domestic Relations)', 'New Hampshire Property Tax Assessment laws'], legalNotes: ['Heavy reliance on property taxes', 'No state income or sales tax', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'new-jersey': { name: 'New Jersey', abbr: 'NJ', icon: '\u{1f330}', topics: ['Tenant Rights', 'Property Tax', 'Business Law', 'Real Estate'], content: 'New Jersey has specific legal requirements for tenant rights, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in New Jersey\n\n### Tenant Rights\New Jersey has some of the strongest tenant protections in the US, including rent control in certain municipalities and just cause eviction requirements.\n\n### Property Tax\New Jersey has the highest property tax rates in the nation. The state has specific assessment and collection procedures with various exemptions available.\n\n### Business Law\New Jersey offers various business entity types and has specific filing requirements with the Division of Revenue and Enterprise Services.\n\n### Real Estate\New Jersey has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['New Jersey Revised Statutes Title 46 (Property and Conveyances)', 'New Jersey Revised Statutes Title 14A (Corporations)', 'New Jersey Revised Statutes Title 2A (Administration of Civil and Criminal Justice)', 'New Jersey Anti-Eviction Act'], legalNotes: ['Strong tenant protections', 'Highest property tax rates', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'new-mexico': { name: 'New Mexico', abbr: 'NM', icon: '\u{1f3dd}\ufe0f', topics: ['Water Rights', 'Property Tax', 'Business Law', 'Real Estate'], content: 'New Mexico has specific legal requirements for water rights, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in New Mexico\n\n### Water Rights\New Mexico follows the prior appropriation doctrine for water rights, which is crucial for real estate and agricultural operations.\n\n### Property Tax\New Mexico has specific property tax assessment and collection procedures. The state offers various exemptions and deferrals for qualifying property owners.\n\n### Business Law\New Mexico offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\New Mexico has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['New Mexico Statutes Annotated Article 47 (Property and Conveyances)', 'New Mexico Statutes Annotated Article 53 (Corporations)', 'New Mexico Statutes Annotated Article 40 (Domestic Relations)', 'New Mexico Water Use Act'], legalNotes: ['Prior appropriation water rights', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'new-york': { name: 'New York', abbr: 'NY', icon: '\u{1f5fd}', topics: ['Rent Stabilization', 'Employment Law', 'Business Regulations', 'Tenant Protections'], content: 'New York has strict rent stabilization laws in NYC and comprehensive employment protections. The state is known for its strong tenant rights and complex regulatory environment.\n\n## Key Legal Areas in New York\n\n### Tenant Protections\New York has extensive tenant protections including rent stabilization in NYC covering about 1 million apartments, the Housing Stability and Tenant Protection Act (HSTPA), and good cause eviction requirements.\n\n### Employment Law\New York has strict employment laws including paid family leave, minimum wage requirements, and anti-discrimination protections.\n\n### Business Regulations\New York has complex business regulations including the NY SHIELD Act for data protection and various industry-specific requirements.\n\n### Real Estate\New York has specific disclosure requirements for real estate transactions and tenant protection laws.', keyLaws: ['New York Real Property Law', 'New York General Obligations Law', 'New York Labor Law', 'Housing Stability and Tenant Protection Act (HSTPA)'], legalNotes: ['Rent stabilization in NYC', 'Security deposit limited to 1 month', 'Good cause eviction law', 'Strong employment protections'] },
  'north-carolina': { name: 'North Carolina', abbr: 'NC', icon: '\u{1f332}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'North Carolina has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in North Carolina\n\n### Property Tax\North Carolina has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\North Carolina offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\North Carolina has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\North Carolina follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['North Carolina General Statutes Chapter 47 (Conveyancing and Recording)', 'North Carolina General Statutes Chapter 55 (North Carolina Business Corporation Act)', 'North Carolina General Statutes Chapter 50 (Divorce and Alimony)', 'North Carolina General Statutes Chapter 105 (Taxation)'], legalNotes: ['Property tax exemptions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'north-dakota': { name: 'North Dakota', abbr: 'ND', icon: '\u2744\ufe0f', topics: ['Oil and Gas', 'Property Tax', 'Business Law', 'Real Estate'], content: 'North Dakota has specific legal requirements for oil and gas law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in North Dakota\n\n### Oil and Gas Law\North Dakota has specific laws governing oil and gas production, including mineral rights, royalty provisions, and environmental regulations.\n\n### Property Tax\North Dakota has specific property tax assessment and collection procedures. The state offers homestead credits for qualifying property owners.\n\n### Business Law\North Dakota offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\North Dakota has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['North Dakota Century Code Title 32 (Conveyancing of Real Property)', 'North Dakota Century Code Title 10 (Corporations)', 'North Dakota Century Code Title 14 (Domestic Relations)', 'North Dakota Oil and Gas Production Tax statutes'], legalNotes: ['Oil and gas law regulations', 'Homestead credits available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'ohio': { name: 'Ohio', abbr: 'OH', icon: '\u{1f333}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'Ohio has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Ohio\n\n### Property Tax\Ohio has specific property tax assessment and collection procedures. The state offers homestead and owner-occupancy exemptions for qualifying property owners.\n\n### Business Law\Ohio offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Ohio has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Ohio follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Ohio Revised Code Title 53 (Real and Personal Property)', 'Ohio Revised Code Title 1707 (Securities and Franchises)', 'Ohio Revised Code Title 3103 (Domestic Relations)', 'Ohio Revised Code Title 57 (Taxation)'], legalNotes: ['Property tax exemptions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'oklahoma': { name: 'Oklahoma', abbr: 'OK', icon: '\u{1f340}', topics: ['Oil and Gas', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Oklahoma has specific legal requirements for oil and gas law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Oklahoma\n\n### Oil and Gas Law\Oklahoma has specific laws governing oil and gas production, including mineral rights, royalty provisions, and environmental regulations.\n\n### Property Tax\Oklahoma has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Oklahoma offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Oklahoma has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Oklahoma Statutes Title 16 (Conveyances)', 'Oklahoma Statutes Title 18 (Corporations)', 'Oklahoma Statutes Title 43 (Marriage)', 'Oklahoma Gross Production Tax statutes'], legalNotes: ['Oil and gas law regulations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'oregon': { name: 'Oregon', abbr: 'OR', icon: '\u{1f332}', topics: ['Rent Control', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Oregon has specific legal requirements for rent control, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Oregon\n\n### Rent Control\Oregon was one of the first states to enact statewide rent control legislation, limiting rent increases and providing tenant protections.\n\n### Property Tax\Oregon has specific property tax assessment and collection procedures. The state offers various exemptions and deferrals for qualifying property owners.\n\n### Business Law\Oregon offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Oregon has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Oregon Revised Statutes Title 93 (Conveyances and Mortgages)', 'Oregon Revised Statutes Title 7 (Corporations and Partnerships)', 'Oregon Revised Statutes Title 107 (Property Rights Between Spouses)', 'Oregon Residential Landlord and Tenant Act'], legalNotes: ['Statewide rent control', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'pennsylvania': { name: 'Pennsylvania', abbr: 'PA', icon: '\u{1f333}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'Pennsylvania has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Pennsylvania\n\n### Property Tax\Pennsylvania has specific property tax assessment and collection procedures. The state offers homestead and farmstead exemptions for qualifying property owners.\n\n### Business Law\Pennsylvania offers various business entity types and has specific filing requirements with the Department of State.\n\n### Real Estate\Pennsylvania has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Pennsylvania follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Pennsylvania Statutes Title 21 (Conveyances and Promissory Notes)', 'Pennsylvania Statutes Title 15 (Corporations and Unincorporated Associations)', 'Pennsylvania Statutes Title 23 (Domestic Relations)', 'Pennsylvania Statutes Title 72 (Taxation and Fiscal Affairs)'], legalNotes: ['Property tax exemptions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'rhode-island': { name: 'Rhode Island', abbr: 'RI', icon: '\u{1f3d9}\ufe0f', topics: ['Maritime Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Rhode Island has specific legal requirements for maritime law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Rhode Island\n\n### Maritime Law\Rhode Island has specific laws governing maritime activities, including boating regulations, fishing rights, and coastal zone management.\n\n### Property Tax\Rhode Island has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\Rhode Island offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Rhode Island has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Rhode Island General Laws Title 34 (Property and Conveyancing)', 'Rhode Island General Laws Title 7 (Corporations, Associations, and Partnerships)', 'Rhode Island General Laws Title 15 (Domestic Relations)', 'Rhode Island General Laws Title 44 (Taxation)'], legalNotes: ['Maritime law considerations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'south-carolina': { name: 'South Carolina', abbr: 'SC', icon: '\u{1f341}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'South Carolina has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in South Carolina\n\n### Property Tax\South Carolina has specific property tax assessment and collection procedures. The state offers homestead exemptions for qualifying property owners.\n\n### Business Law\South Carolina offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\South Carolina has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\South Carolina follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['South Carolina Code of Laws Title 27 (Conveyances)', 'South Carolina Code of Laws Title 33 (Corporations, Partnerships, and Associations)', 'South Carolina Code of Laws Title 63 (South Carolina Children\'s Code)', 'South Carolina Code of Laws Title 12 (Taxation)'], legalNotes: ['Property tax exemptions available', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'south-dakota': { name: 'South Dakota', abbr: 'SD', icon: '\u{1f33e}', topics: ['Trust Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'South Dakota has specific legal requirements for trust law, property tax, and business formation. The state is known for its trust-friendly laws and unique statutory provisions.\n\n## Key Legal Areas in South Dakota\n\n### Trust Law\South Dakota has some of the most trust-friendly laws in the US, including dynasty trusts, asset protection trusts, and favorable tax treatment for trust income.\n\n### Property Tax\South Dakota has specific property tax assessment and collection procedures. The state offers various exemptions for qualifying property owners.\n\n### Business Law\South Dakota offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\South Dakota has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['South Dakota Codified Laws Title 43A (Trusts)', 'South Dakota Codified Laws Title 47 (Corporations)', 'South Dakota Codified Laws Title 25 (Marriage)', 'South Dakota Codified Laws Title 10 (Conveyances)'], legalNotes: ['Trust-friendly laws', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'tennessee': { name: 'Tennessee', abbr: 'TN', icon: '\u{1f333}', topics: ['No State Income Tax', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Tennessee has specific legal requirements related to its lack of state income tax, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Tennessee\n\n### Tax Structure\Tennessee has no state income tax on wages, making it attractive for workers and retirees. The state has a Hall Income Tax on investment income being phased out.\n\n### Property Tax\Tennessee has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\Tennessee offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Tennessee has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Tennessee Code Annotated Title 66 (Transfers of Real Property)', 'Tennessee Code Annotated Title 48 (Corporations, Partnerships, and Associations)', 'Tennessee Code Annotated Title 36 (Domestic Relations)', 'Tennessee Code Annotated Title 67 (Taxation and Revenue)'], legalNotes: ['No state income tax on wages', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'texas': { name: 'Texas', abbr: 'TX', icon: '\u2b50', topics: ['Property Tax', 'Business Friendly', 'No State Income Tax', 'Property Rights'], content: 'Texas is known for its business-friendly environment with no state income tax and relatively low regulations. The state has strong property rights protections and a growing economy.\n\n## Key Legal Areas in Texas\n\n### Property Tax\Texas relies heavily on property taxes for revenue since there is no state income tax. Property tax rates vary by county and can be significant.\n\n### Business Law\Texas is considered one of the most business-friendly states with no state income tax, limited regulations, and strong contract enforcement.\n\n### Real Estate\Texas has specific requirements for real estate transactions including disclosure requirements and title insurance regulations.\n\n### Employment Law\Texas follows the at-will employment doctrine with limited exceptions. The state has its own anti-discrimination laws and workers compensation system.', keyLaws: ['Texas Property Code', 'Texas Business and Commerce Code', 'Texas Labor Code', 'Texas Tax Code'], legalNotes: ['No state income tax', 'Property tax rates vary by county', 'No rent control anywhere in the state', 'At-will employment with limited exceptions'] },
  'utah': { name: 'Utah', abbr: 'UT', icon: '\u26f0\ufe0f', topics: ['Property Rights', 'Business Law', 'Real Estate', 'Family Law'], content: 'Utah has specific legal requirements for property rights, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Utah\n\n### Property Rights\Utah has specific property rights protections and unique requirements for property transfers and recording.\n\n### Business Law\Utah offers various business entity types and has specific filing requirements with the Division of Corporations and Commercial Code.\n\n### Real Estate\Utah has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Utah follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Utah Code Title 57 (Real Estate)', 'Utah Code Title 16 (Corporations and Associations)', 'Utah Code Title 30 (Domestic Relations)', 'Utah Code Title 59 (Revenue and Taxation)'], legalNotes: ['Specific property transfer requirements', 'Business-friendly environment', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'vermont': { name: 'Vermont', abbr: 'VT', icon: '\u{1f341}', topics: ['Land Use', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Vermont has specific legal requirements for land use, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Vermont\n\n### Land Use\Vermont has specific laws governing land use, including Act 250 (a statewide environmental review process for large developments) and local zoning regulations.\n\n### Property Tax\Vermont has specific property tax assessment and collection procedures. The state offers various exemptions and use-value appraisals for qualifying property owners.\n\n### Business Law\Vermont offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Vermont has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Vermont Statutes Title 27 (Property and Conveyances)', 'Vermont Statutes Title 11A (Vermont Business Corporation Act)', 'Vermont Statutes Title 15 (Domestic Relations)', 'Vermont Statutes Title 32 (Taxation and Assessment)'], legalNotes: ['Act 250 land use review', 'Property tax exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'virginia': { name: 'Virginia', abbr: 'VA', icon: '\u{1f333}', topics: ['Property Tax', 'Business Law', 'Real Estate', 'Family Law'], content: 'Virginia has specific legal requirements for property tax, business formation, and family law matters. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Virginia\n\n### Property Tax\Virginia has specific property tax assessment and collection procedures. The state offers various exemptions for qualifying property owners.\n\n### Business Law\Virginia offers various business entity types and has specific filing requirements with the State Corporation Commission.\n\n### Real Estate\Virginia has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Family Law\Virginia follows equitable distribution for property division in divorce cases and has specific child custody guidelines.', keyLaws: ['Virginia Code Title 55.1 (Conveyances)', 'Virginia Code Title 13.1 (Corporations)', 'Virginia Code Title 20 (Domestic Relations)', 'Virginia Code Title 58.1 (Taxation)'], legalNotes: ['Property tax exemptions available', 'Business filing requirements', 'Equitable distribution in divorce', 'Real estate disclosure requirements'] },
  'washington': { name: 'Washington', abbr: 'WA', icon: '\u{1f332}', topics: ['Tenant Rights', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Washington has specific legal requirements for tenant rights, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Washington\n\n### Tenant Rights\Washington has specific tenant protections including just cause eviction requirements and security deposit regulations.\n\n### Property Tax\Washington has specific property tax assessment and collection procedures. The state offers various exemptions for qualifying property owners.\n\n### Business Law\Washington offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Washington has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Washington Revised Code Title 64 (Real Property and Conveyances)', 'Washington Revised Code Title 23B (Washington Business Corporation Act)', 'Washington Revised Code Title 26 (Domestic Relations)', 'Washington Revised Code Title 84 (Property Tax)'], legalNotes: ['Tenant protection laws', 'Property tax exemptions available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'west-virginia': { name: 'West Virginia', abbr: 'WV', icon: '\u26f0\ufe0f', topics: ['Coal Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'West Virginia has specific legal requirements for coal law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in West Virginia\n\n### Coal Law\West Virginia has specific laws governing coal mining operations, including environmental regulations, reclamation requirements, and miner safety.\n\n### Property Tax\West Virginia has specific property tax assessment and collection procedures. The state offers homestead and other exemptions for qualifying property owners.\n\n### Business Law\West Virginia offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\West Virginia has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['West Virginia Code Chapter 36 (Estates and Fiduciaries)', 'West Virginia Code Chapter 31 (Corporations)', 'West Virginia Code Chapter 48 (Domestic Relations)', 'West Virginia Coal Mining Safety Act'], legalNotes: ['Coal mining regulations', 'Homestead exemptions available', 'Business-friendly environment', 'Real estate disclosure requirements'] },
  'wisconsin': { name: 'Wisconsin', abbr: 'WI', icon: '\u{1f342}', topics: ['Dairy Law', 'Property Tax', 'Business Law', 'Real Estate'], content: 'Wisconsin has specific legal requirements for dairy law, property tax, and business formation. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Wisconsin\n\n### Dairy Law\Wisconsin has specific laws governing dairy operations, including production standards, marketing regulations, and cooperative structures.\n\n### Property Tax\Wisconsin has specific property tax assessment and collection procedures. The state offers various exemptions for qualifying property owners.\n\n### Business Law\Wisconsin offers various business entity types and has specific filing requirements with the Department of Financial Institutions.\n\n### Real Estate\Wisconsin has specific disclosure requirements for real estate transactions and unique property transfer procedures.', keyLaws: ['Wisconsin Statutes Chapter 706 (Conveyances of Real Property)', 'Wisconsin Statutes Chapter 180 (Wisconsin Business Corporation Law)', 'Wisconsin Statutes Chapter 767 (Actions Affecting the Family)', 'Wisconsin Statutes Chapter 70 (Taxation)'], legalNotes: ['Dairy law regulations', 'Property tax exemptions available', 'Business filing requirements', 'Real estate disclosure requirements'] },
  'wyoming': { name: 'Wyoming', abbr: 'WY', icon: '\u{1f3d9}\ufe0f', topics: ['Property Rights', 'Business Law', 'Real Estate', 'Energy Law'], content: 'Wyoming has specific legal requirements for property rights, business formation, and energy law. The state has unique statutory provisions governing property and business operations.\n\n## Key Legal Areas in Wyoming\n\n### Property Rights\Wyoming has specific property rights protections and unique requirements for property transfers and recording.\n\n### Business Law\Wyoming offers various business entity types and has specific filing requirements with the Secretary of State.\n\n### Real Estate\Wyoming has specific disclosure requirements for real estate transactions and unique property transfer procedures.\n\n### Energy Law\Wyoming has specific laws governing energy production, including coal, oil, gas, and renewable energy regulations.', keyLaws: ['Wyoming Statutes Title 34 (Property, Conveyances and Encumbrances)', 'Wyoming Statutes Title 17 (Corporations)', 'Wyoming Statutes Title 20 (Domestic Relations)', 'Wyoming Energy Laws'], legalNotes: ['Energy law regulations', 'Specific property transfer requirements', 'Business-friendly environment', 'Real estate disclosure requirements'] },
};

export async function generateStaticParams() {
  return Object.keys(guides).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const guide = guides[slug];
  if (!guide) return { title: 'Not Found' };
  return { title: `${guide.name} Law Guide | LegalDocs`, description: `Comprehensive guide to ${guide.name} legal requirements including ${guide.topics.join(', ')}.` };
}

export default async function GuideStatePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const guide = guides[slug];
  if (!guide) notFound();

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="mx-auto max-w-7xl px-4 py-3">
          <nav className="text-sm text-gray-500">
            <Link href="/" className="hover:text-blue-600">Home</Link><span className="mx-2">/</span>
            <Link href="/guides" className="hover:text-blue-600">Guides</Link><span className="mx-2">/</span>
            <span className="text-gray-900">{guide.name}</span>
          </nav>
        </div>
      </div>
      <section className="bg-gradient-to-r from-blue-600 to-indigo-700 py-12">
        <div className="mx-auto max-w-7xl px-4 text-center">
          <div className="text-5xl mb-4">{guide.icon}</div>
          <h1 className="text-3xl font-bold text-white">{guide.name} Law Guide</h1>
          <p className="mt-2 text-blue-100">Comprehensive legal requirements and regulations for {guide.name}</p>
          <div className="mt-4 flex flex-wrap justify-center gap-2">
            {guide.topics.map((topic) => (
              <span key={topic} className="rounded-full bg-white/20 px-3 py-1 text-sm text-white">{topic}</span>
            ))}
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-4xl px-4 py-12">
        <div className="rounded-xl border border-gray-200 bg-white p-8 shadow-sm">
          <h2 className="mb-4 text-2xl font-bold text-gray-900">Overview of {guide.name} Law</h2>
          <div className="prose prose-gray max-w-none">
            {guide.content.split('\n\n').map((paragraph, i) => {
              if (paragraph.startsWith('## ')) {
                return <h3 key={i} className="text-xl font-bold text-gray-900 mt-6 mb-3">{paragraph.replace('## ', '')}</h3>;
              }
              if (paragraph.startsWith('### ')) {
                return <h4 key={i} className="text-lg font-bold text-gray-900 mt-4 mb-2">{paragraph.replace('### ', '')}</h4>;
              }
              return <p key={i} className="mb-4 text-gray-700 leading-relaxed">{paragraph}</p>;
            })}
          </div>
          <div className="mt-8">
            <h3 className="mb-4 text-xl font-bold text-gray-900">Key Laws in {guide.name}</h3>
            <ul className="space-y-2">
              {guide.keyLaws.map((law) => (
                <li key={law} className="flex items-start gap-2">
                  <span className="mt-1 text-blue-600">&#9679;</span>
                  <span className="text-gray-700">{law}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-8">
            <h3 className="mb-4 text-xl font-bold text-gray-900">Important Legal Notes for {guide.name}</h3>
            <ul className="space-y-2">
              {guide.legalNotes.map((note) => (
                <li key={note} className="flex items-start gap-2">
                  <span className="mt-1 text-green-500">&#10003;</span>
                  <span className="text-gray-700">{note}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-8">
            <h3 className="mb-4 text-xl font-bold text-gray-900">Legal Documents for {guide.name}</h3>
            <p className="mb-4 text-gray-700">Browse our free, state-specific legal document templates customized for {guide.name} law. Each template includes state-specific legal requirements and compliance information.</p>
            <Link href="/" className="inline-block rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white transition hover:bg-blue-700">Browse Documents for {guide.name}</Link>
          </div>
        </div>
        <div className="mt-8 rounded-xl bg-blue-50 p-6">
          <h3 className="mb-3 text-lg font-bold text-gray-900">Related Resources</h3>
          <div className="flex flex-wrap gap-2">
            <Link href="/directory" className="rounded-lg bg-white px-4 py-2 text-sm text-gray-700 shadow-sm hover:shadow-md">Legal Directory</Link>
            <Link href="/blog" className="rounded-lg bg-white px-4 py-2 text-sm text-gray-700 shadow-sm hover:shadow-md">Legal Blog</Link>
            <Link href="/guides" className="rounded-lg bg-white px-4 py-2 text-sm text-gray-700 shadow-sm hover:shadow-md">All State Guides</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
